// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_organization_project_membership_permission

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework-validators/listvalidator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"regexp"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func OrganizationProjectMembershipPermissionResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"member_id": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"organization_id": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"project_id": schema.StringAttribute{
				Optional: true,
				Computed: true,
				Validators: []validator.String{
					stringvalidator.RegexMatches(regexp.MustCompile("^[a-f0-9]{8}[a-f0-9]{4}4[a-f0-9]{3}[89ab][a-f0-9]{3}[a-f0-9]{12}$"), ""),
				},
			},
			"service_account_membership": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"membership_type": schema.StringAttribute{
						Computed:            true,
						Description:         "The type of the membership.",
						MarkdownDescription: "The type of the membership.",
						Default:             stringdefault.StaticString("service_account"),
					},
					"permissions": schema.ListAttribute{
						ElementType:         types.StringType,
						Computed:            true,
						Description:         "The permissions of the service account",
						MarkdownDescription: "The permissions of the service account",
					},
					"project": schema.SingleNestedAttribute{
						Attributes: map[string]schema.Attribute{
							"created_at": schema.StringAttribute{
								Computed:            true,
								Description:         "The time the resource was created.",
								MarkdownDescription: "The time the resource was created.",
							},
							"description": schema.StringAttribute{
								Computed:            true,
								Description:         "The description of the project.",
								MarkdownDescription: "The description of the project.",
								Default:             stringdefault.StaticString(""),
							},
							"id": schema.StringAttribute{
								Computed:            true,
								Description:         "The unique identifier of the project, as inherited from OpenStack",
								MarkdownDescription: "The unique identifier of the project, as inherited from OpenStack",
							},
							"name": schema.StringAttribute{
								Computed:            true,
								Description:         "The name of the project.",
								MarkdownDescription: "The name of the project.",
							},
							"tags": schema.ListAttribute{
								ElementType:         types.StringType,
								Computed:            true,
								Description:         "The tags of the project.",
								MarkdownDescription: "The tags of the project.",
							},
							"updated_at": schema.StringAttribute{
								Computed:            true,
								Description:         "The time the resource was last updated.",
								MarkdownDescription: "The time the resource was last updated.",
							},
						},
						CustomType: ProjectType{
							ObjectType: types.ObjectType{
								AttrTypes: ProjectValue{}.AttributeTypes(ctx),
							},
						},
						Computed: true,
					},
					"service_account": schema.SingleNestedAttribute{
						Attributes: map[string]schema.Attribute{
							"created_at": schema.StringAttribute{
								Computed:            true,
								Description:         "The time the resource was created.",
								MarkdownDescription: "The time the resource was created.",
							},
							"description": schema.StringAttribute{
								Computed:            true,
								Description:         "The description of the service account.",
								MarkdownDescription: "The description of the service account.",
								Default:             stringdefault.StaticString(""),
							},
							"id": schema.StringAttribute{
								Computed:            true,
								Description:         "The UUID of the service account.",
								MarkdownDescription: "The UUID of the service account.",
							},
							"name": schema.StringAttribute{
								Computed:            true,
								Description:         "The unique name of the service account.",
								MarkdownDescription: "The unique name of the service account.",
							},
							"updated_at": schema.StringAttribute{
								Computed:            true,
								Description:         "The time the resource was last updated.",
								MarkdownDescription: "The time the resource was last updated.",
							},
						},
						CustomType: ServiceAccountType{
							ObjectType: types.ObjectType{
								AttrTypes: ServiceAccountValue{}.AttributeTypes(ctx),
							},
						},
						Computed: true,
					},
				},
				CustomType: ServiceAccountMembershipType{
					ObjectType: types.ObjectType{
						AttrTypes: ServiceAccountMembershipValue{}.AttributeTypes(ctx),
					},
				},
				Computed: true,
			},
			"service_account_permissions": schema.ListAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Computed:    true,
				Validators: []validator.List{
					listvalidator.UniqueValues(),
				},
			},
			"user_membership": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"membership_type": schema.StringAttribute{
						Computed:            true,
						Description:         "The type of the membership.",
						MarkdownDescription: "The type of the membership.",
						Default:             stringdefault.StaticString("user"),
					},
					"permissions": schema.ListAttribute{
						ElementType:         types.StringType,
						Computed:            true,
						Description:         "The permissions of the user",
						MarkdownDescription: "The permissions of the user",
					},
					"project": schema.SingleNestedAttribute{
						Attributes: map[string]schema.Attribute{
							"created_at": schema.StringAttribute{
								Computed:            true,
								Description:         "The time the resource was created.",
								MarkdownDescription: "The time the resource was created.",
							},
							"description": schema.StringAttribute{
								Computed:            true,
								Description:         "The description of the project.",
								MarkdownDescription: "The description of the project.",
								Default:             stringdefault.StaticString(""),
							},
							"id": schema.StringAttribute{
								Computed:            true,
								Description:         "The unique identifier of the project, as inherited from OpenStack",
								MarkdownDescription: "The unique identifier of the project, as inherited from OpenStack",
							},
							"name": schema.StringAttribute{
								Computed:            true,
								Description:         "The name of the project.",
								MarkdownDescription: "The name of the project.",
							},
							"tags": schema.ListAttribute{
								ElementType:         types.StringType,
								Computed:            true,
								Description:         "The tags of the project.",
								MarkdownDescription: "The tags of the project.",
							},
							"updated_at": schema.StringAttribute{
								Computed:            true,
								Description:         "The time the resource was last updated.",
								MarkdownDescription: "The time the resource was last updated.",
							},
						},
						CustomType: ProjectType{
							ObjectType: types.ObjectType{
								AttrTypes: ProjectValue{}.AttributeTypes(ctx),
							},
						},
						Computed: true,
					},
					"project_id": schema.StringAttribute{
						Computed:            true,
						Description:         "DEPRECATED: The UUID of the project",
						MarkdownDescription: "DEPRECATED: The UUID of the project",
					},
					"project_name": schema.StringAttribute{
						Computed:            true,
						Description:         "DEPRECATED: The name of the project",
						MarkdownDescription: "DEPRECATED: The name of the project",
					},
					"user": schema.SingleNestedAttribute{
						Attributes: map[string]schema.Attribute{
							"email": schema.StringAttribute{
								Computed:            true,
								Description:         "The email address of the user.",
								MarkdownDescription: "The email address of the user.",
							},
							"id": schema.StringAttribute{
								Computed:            true,
								Description:         "The UUID of the user.",
								MarkdownDescription: "The UUID of the user.",
							},
						},
						CustomType: UserType{
							ObjectType: types.ObjectType{
								AttrTypes: UserValue{}.AttributeTypes(ctx),
							},
						},
						Computed: true,
					},
				},
				CustomType: UserMembershipType{
					ObjectType: types.ObjectType{
						AttrTypes: UserMembershipValue{}.AttributeTypes(ctx),
					},
				},
				Computed: true,
			},
			"user_permissions": schema.ListAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Computed:    true,
				Validators: []validator.List{
					listvalidator.UniqueValues(),
				},
			},
		},
	}
}

type OrganizationProjectMembershipPermissionModel struct {
	MemberId                  types.String                  `tfsdk:"member_id"`
	OrganizationId            types.String                  `tfsdk:"organization_id"`
	ProjectId                 types.String                  `tfsdk:"project_id"`
	ServiceAccountMembership  ServiceAccountMembershipValue `tfsdk:"service_account_membership"`
	ServiceAccountPermissions types.List                    `tfsdk:"service_account_permissions"`
	UserMembership            UserMembershipValue           `tfsdk:"user_membership"`
	UserPermissions           types.List                    `tfsdk:"user_permissions"`
}

var _ basetypes.ObjectTypable = ServiceAccountMembershipType{}

type ServiceAccountMembershipType struct {
	basetypes.ObjectType
}

func (t ServiceAccountMembershipType) Equal(o attr.Type) bool {
	other, ok := o.(ServiceAccountMembershipType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t ServiceAccountMembershipType) String() string {
	return "ServiceAccountMembershipType"
}

func (t ServiceAccountMembershipType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	membershipTypeAttribute, ok := attributes["membership_type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`membership_type is missing from object`)

		return nil, diags
	}

	membershipTypeVal, ok := membershipTypeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`membership_type expected to be basetypes.StringValue, was: %T`, membershipTypeAttribute))
	}

	permissionsAttribute, ok := attributes["permissions"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`permissions is missing from object`)

		return nil, diags
	}

	permissionsVal, ok := permissionsAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`permissions expected to be basetypes.ListValue, was: %T`, permissionsAttribute))
	}

	projectAttribute, ok := attributes["project"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`project is missing from object`)

		return nil, diags
	}

	projectVal, ok := projectAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`project expected to be basetypes.ObjectValue, was: %T`, projectAttribute))
	}

	serviceAccountAttribute, ok := attributes["service_account"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`service_account is missing from object`)

		return nil, diags
	}

	serviceAccountVal, ok := serviceAccountAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`service_account expected to be basetypes.ObjectValue, was: %T`, serviceAccountAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return ServiceAccountMembershipValue{
		MembershipType: membershipTypeVal,
		Permissions:    permissionsVal,
		Project:        projectVal,
		ServiceAccount: serviceAccountVal,
		state:          attr.ValueStateKnown,
	}, diags
}

func NewServiceAccountMembershipValueNull() ServiceAccountMembershipValue {
	return ServiceAccountMembershipValue{
		state: attr.ValueStateNull,
	}
}

func NewServiceAccountMembershipValueUnknown() ServiceAccountMembershipValue {
	return ServiceAccountMembershipValue{
		state: attr.ValueStateUnknown,
	}
}

func NewServiceAccountMembershipValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (ServiceAccountMembershipValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing ServiceAccountMembershipValue Attribute Value",
				"While creating a ServiceAccountMembershipValue value, a missing attribute value was detected. "+
					"A ServiceAccountMembershipValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ServiceAccountMembershipValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid ServiceAccountMembershipValue Attribute Type",
				"While creating a ServiceAccountMembershipValue value, an invalid attribute value was detected. "+
					"A ServiceAccountMembershipValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ServiceAccountMembershipValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("ServiceAccountMembershipValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra ServiceAccountMembershipValue Attribute Value",
				"While creating a ServiceAccountMembershipValue value, an extra attribute value was detected. "+
					"A ServiceAccountMembershipValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra ServiceAccountMembershipValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewServiceAccountMembershipValueUnknown(), diags
	}

	membershipTypeAttribute, ok := attributes["membership_type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`membership_type is missing from object`)

		return NewServiceAccountMembershipValueUnknown(), diags
	}

	membershipTypeVal, ok := membershipTypeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`membership_type expected to be basetypes.StringValue, was: %T`, membershipTypeAttribute))
	}

	permissionsAttribute, ok := attributes["permissions"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`permissions is missing from object`)

		return NewServiceAccountMembershipValueUnknown(), diags
	}

	permissionsVal, ok := permissionsAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`permissions expected to be basetypes.ListValue, was: %T`, permissionsAttribute))
	}

	projectAttribute, ok := attributes["project"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`project is missing from object`)

		return NewServiceAccountMembershipValueUnknown(), diags
	}

	projectVal, ok := projectAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`project expected to be basetypes.ObjectValue, was: %T`, projectAttribute))
	}

	serviceAccountAttribute, ok := attributes["service_account"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`service_account is missing from object`)

		return NewServiceAccountMembershipValueUnknown(), diags
	}

	serviceAccountVal, ok := serviceAccountAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`service_account expected to be basetypes.ObjectValue, was: %T`, serviceAccountAttribute))
	}

	if diags.HasError() {
		return NewServiceAccountMembershipValueUnknown(), diags
	}

	return ServiceAccountMembershipValue{
		MembershipType: membershipTypeVal,
		Permissions:    permissionsVal,
		Project:        projectVal,
		ServiceAccount: serviceAccountVal,
		state:          attr.ValueStateKnown,
	}, diags
}

func NewServiceAccountMembershipValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) ServiceAccountMembershipValue {
	object, diags := NewServiceAccountMembershipValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewServiceAccountMembershipValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t ServiceAccountMembershipType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewServiceAccountMembershipValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewServiceAccountMembershipValueUnknown(), nil
	}

	if in.IsNull() {
		return NewServiceAccountMembershipValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewServiceAccountMembershipValueMust(ServiceAccountMembershipValue{}.AttributeTypes(ctx), attributes), nil
}

func (t ServiceAccountMembershipType) ValueType(ctx context.Context) attr.Value {
	return ServiceAccountMembershipValue{}
}

var _ basetypes.ObjectValuable = ServiceAccountMembershipValue{}

type ServiceAccountMembershipValue struct {
	MembershipType basetypes.StringValue `tfsdk:"membership_type"`
	Permissions    basetypes.ListValue   `tfsdk:"permissions"`
	Project        basetypes.ObjectValue `tfsdk:"project"`
	ServiceAccount basetypes.ObjectValue `tfsdk:"service_account"`
	state          attr.ValueState
}

func (v ServiceAccountMembershipValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 4)

	var val tftypes.Value
	var err error

	attrTypes["membership_type"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["permissions"] = basetypes.ListType{
		ElemType: types.StringType,
	}.TerraformType(ctx)
	attrTypes["project"] = basetypes.ObjectType{
		AttrTypes: ProjectValue{}.AttributeTypes(ctx),
	}.TerraformType(ctx)
	attrTypes["service_account"] = basetypes.ObjectType{
		AttrTypes: ServiceAccountValue{}.AttributeTypes(ctx),
	}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 4)

		val, err = v.MembershipType.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["membership_type"] = val

		val, err = v.Permissions.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["permissions"] = val

		val, err = v.Project.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["project"] = val

		val, err = v.ServiceAccount.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["service_account"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v ServiceAccountMembershipValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v ServiceAccountMembershipValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v ServiceAccountMembershipValue) String() string {
	return "ServiceAccountMembershipValue"
}

func (v ServiceAccountMembershipValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	var project basetypes.ObjectValue

	if v.Project.IsNull() {
		project = types.ObjectNull(
			ProjectValue{}.AttributeTypes(ctx),
		)
	}

	if v.Project.IsUnknown() {
		project = types.ObjectUnknown(
			ProjectValue{}.AttributeTypes(ctx),
		)
	}

	if !v.Project.IsNull() && !v.Project.IsUnknown() {
		project = types.ObjectValueMust(
			ProjectValue{}.AttributeTypes(ctx),
			v.Project.Attributes(),
		)
	}

	var serviceAccount basetypes.ObjectValue

	if v.ServiceAccount.IsNull() {
		serviceAccount = types.ObjectNull(
			ServiceAccountValue{}.AttributeTypes(ctx),
		)
	}

	if v.ServiceAccount.IsUnknown() {
		serviceAccount = types.ObjectUnknown(
			ServiceAccountValue{}.AttributeTypes(ctx),
		)
	}

	if !v.ServiceAccount.IsNull() && !v.ServiceAccount.IsUnknown() {
		serviceAccount = types.ObjectValueMust(
			ServiceAccountValue{}.AttributeTypes(ctx),
			v.ServiceAccount.Attributes(),
		)
	}

	var permissionsVal basetypes.ListValue
	switch {
	case v.Permissions.IsUnknown():
		permissionsVal = types.ListUnknown(types.StringType)
	case v.Permissions.IsNull():
		permissionsVal = types.ListNull(types.StringType)
	default:
		var d diag.Diagnostics
		permissionsVal, d = types.ListValue(types.StringType, v.Permissions.Elements())
		diags.Append(d...)
	}

	if diags.HasError() {
		return types.ObjectUnknown(map[string]attr.Type{
			"membership_type": basetypes.StringType{},
			"permissions": basetypes.ListType{
				ElemType: types.StringType,
			},
			"project": basetypes.ObjectType{
				AttrTypes: ProjectValue{}.AttributeTypes(ctx),
			},
			"service_account": basetypes.ObjectType{
				AttrTypes: ServiceAccountValue{}.AttributeTypes(ctx),
			},
		}), diags
	}

	attributeTypes := map[string]attr.Type{
		"membership_type": basetypes.StringType{},
		"permissions": basetypes.ListType{
			ElemType: types.StringType,
		},
		"project": basetypes.ObjectType{
			AttrTypes: ProjectValue{}.AttributeTypes(ctx),
		},
		"service_account": basetypes.ObjectType{
			AttrTypes: ServiceAccountValue{}.AttributeTypes(ctx),
		},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"membership_type": v.MembershipType,
			"permissions":     permissionsVal,
			"project":         project,
			"service_account": serviceAccount,
		})

	return objVal, diags
}

func (v ServiceAccountMembershipValue) Equal(o attr.Value) bool {
	other, ok := o.(ServiceAccountMembershipValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.MembershipType.Equal(other.MembershipType) {
		return false
	}

	if !v.Permissions.Equal(other.Permissions) {
		return false
	}

	if !v.Project.Equal(other.Project) {
		return false
	}

	if !v.ServiceAccount.Equal(other.ServiceAccount) {
		return false
	}

	return true
}

func (v ServiceAccountMembershipValue) Type(ctx context.Context) attr.Type {
	return ServiceAccountMembershipType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v ServiceAccountMembershipValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"membership_type": basetypes.StringType{},
		"permissions": basetypes.ListType{
			ElemType: types.StringType,
		},
		"project": basetypes.ObjectType{
			AttrTypes: ProjectValue{}.AttributeTypes(ctx),
		},
		"service_account": basetypes.ObjectType{
			AttrTypes: ServiceAccountValue{}.AttributeTypes(ctx),
		},
	}
}

var _ basetypes.ObjectTypable = ProjectType{}

type ProjectType struct {
	basetypes.ObjectType
}

func (t ProjectType) Equal(o attr.Type) bool {
	other, ok := o.(ProjectType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t ProjectType) String() string {
	return "ProjectType"
}

func (t ProjectType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	createdAtAttribute, ok := attributes["created_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`created_at is missing from object`)

		return nil, diags
	}

	createdAtVal, ok := createdAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`created_at expected to be basetypes.StringValue, was: %T`, createdAtAttribute))
	}

	descriptionAttribute, ok := attributes["description"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`description is missing from object`)

		return nil, diags
	}

	descriptionVal, ok := descriptionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`description expected to be basetypes.StringValue, was: %T`, descriptionAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return nil, diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	tagsAttribute, ok := attributes["tags"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`tags is missing from object`)

		return nil, diags
	}

	tagsVal, ok := tagsAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`tags expected to be basetypes.ListValue, was: %T`, tagsAttribute))
	}

	updatedAtAttribute, ok := attributes["updated_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`updated_at is missing from object`)

		return nil, diags
	}

	updatedAtVal, ok := updatedAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`updated_at expected to be basetypes.StringValue, was: %T`, updatedAtAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return ProjectValue{
		CreatedAt:   createdAtVal,
		Description: descriptionVal,
		Id:          idVal,
		Name:        nameVal,
		Tags:        tagsVal,
		UpdatedAt:   updatedAtVal,
		state:       attr.ValueStateKnown,
	}, diags
}

func NewProjectValueNull() ProjectValue {
	return ProjectValue{
		state: attr.ValueStateNull,
	}
}

func NewProjectValueUnknown() ProjectValue {
	return ProjectValue{
		state: attr.ValueStateUnknown,
	}
}

func NewProjectValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (ProjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing ProjectValue Attribute Value",
				"While creating a ProjectValue value, a missing attribute value was detected. "+
					"A ProjectValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ProjectValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid ProjectValue Attribute Type",
				"While creating a ProjectValue value, an invalid attribute value was detected. "+
					"A ProjectValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ProjectValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("ProjectValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra ProjectValue Attribute Value",
				"While creating a ProjectValue value, an extra attribute value was detected. "+
					"A ProjectValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra ProjectValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewProjectValueUnknown(), diags
	}

	createdAtAttribute, ok := attributes["created_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`created_at is missing from object`)

		return NewProjectValueUnknown(), diags
	}

	createdAtVal, ok := createdAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`created_at expected to be basetypes.StringValue, was: %T`, createdAtAttribute))
	}

	descriptionAttribute, ok := attributes["description"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`description is missing from object`)

		return NewProjectValueUnknown(), diags
	}

	descriptionVal, ok := descriptionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`description expected to be basetypes.StringValue, was: %T`, descriptionAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return NewProjectValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return NewProjectValueUnknown(), diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	tagsAttribute, ok := attributes["tags"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`tags is missing from object`)

		return NewProjectValueUnknown(), diags
	}

	tagsVal, ok := tagsAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`tags expected to be basetypes.ListValue, was: %T`, tagsAttribute))
	}

	updatedAtAttribute, ok := attributes["updated_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`updated_at is missing from object`)

		return NewProjectValueUnknown(), diags
	}

	updatedAtVal, ok := updatedAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`updated_at expected to be basetypes.StringValue, was: %T`, updatedAtAttribute))
	}

	if diags.HasError() {
		return NewProjectValueUnknown(), diags
	}

	return ProjectValue{
		CreatedAt:   createdAtVal,
		Description: descriptionVal,
		Id:          idVal,
		Name:        nameVal,
		Tags:        tagsVal,
		UpdatedAt:   updatedAtVal,
		state:       attr.ValueStateKnown,
	}, diags
}

func NewProjectValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) ProjectValue {
	object, diags := NewProjectValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewProjectValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t ProjectType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewProjectValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewProjectValueUnknown(), nil
	}

	if in.IsNull() {
		return NewProjectValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewProjectValueMust(ProjectValue{}.AttributeTypes(ctx), attributes), nil
}

func (t ProjectType) ValueType(ctx context.Context) attr.Value {
	return ProjectValue{}
}

var _ basetypes.ObjectValuable = ProjectValue{}

type ProjectValue struct {
	CreatedAt   basetypes.StringValue `tfsdk:"created_at"`
	Description basetypes.StringValue `tfsdk:"description"`
	Id          basetypes.StringValue `tfsdk:"id"`
	Name        basetypes.StringValue `tfsdk:"name"`
	Tags        basetypes.ListValue   `tfsdk:"tags"`
	UpdatedAt   basetypes.StringValue `tfsdk:"updated_at"`
	state       attr.ValueState
}

func (v ProjectValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 6)

	var val tftypes.Value
	var err error

	attrTypes["created_at"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["description"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["tags"] = basetypes.ListType{
		ElemType: types.StringType,
	}.TerraformType(ctx)
	attrTypes["updated_at"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 6)

		val, err = v.CreatedAt.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["created_at"] = val

		val, err = v.Description.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["description"] = val

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		val, err = v.Name.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["name"] = val

		val, err = v.Tags.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["tags"] = val

		val, err = v.UpdatedAt.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["updated_at"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v ProjectValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v ProjectValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v ProjectValue) String() string {
	return "ProjectValue"
}

func (v ProjectValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	var tagsVal basetypes.ListValue
	switch {
	case v.Tags.IsUnknown():
		tagsVal = types.ListUnknown(types.StringType)
	case v.Tags.IsNull():
		tagsVal = types.ListNull(types.StringType)
	default:
		var d diag.Diagnostics
		tagsVal, d = types.ListValue(types.StringType, v.Tags.Elements())
		diags.Append(d...)
	}

	if diags.HasError() {
		return types.ObjectUnknown(map[string]attr.Type{
			"created_at":  basetypes.StringType{},
			"description": basetypes.StringType{},
			"id":          basetypes.StringType{},
			"name":        basetypes.StringType{},
			"tags": basetypes.ListType{
				ElemType: types.StringType,
			},
			"updated_at": basetypes.StringType{},
		}), diags
	}

	attributeTypes := map[string]attr.Type{
		"created_at":  basetypes.StringType{},
		"description": basetypes.StringType{},
		"id":          basetypes.StringType{},
		"name":        basetypes.StringType{},
		"tags": basetypes.ListType{
			ElemType: types.StringType,
		},
		"updated_at": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"created_at":  v.CreatedAt,
			"description": v.Description,
			"id":          v.Id,
			"name":        v.Name,
			"tags":        tagsVal,
			"updated_at":  v.UpdatedAt,
		})

	return objVal, diags
}

func (v ProjectValue) Equal(o attr.Value) bool {
	other, ok := o.(ProjectValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.CreatedAt.Equal(other.CreatedAt) {
		return false
	}

	if !v.Description.Equal(other.Description) {
		return false
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.Name.Equal(other.Name) {
		return false
	}

	if !v.Tags.Equal(other.Tags) {
		return false
	}

	if !v.UpdatedAt.Equal(other.UpdatedAt) {
		return false
	}

	return true
}

func (v ProjectValue) Type(ctx context.Context) attr.Type {
	return ProjectType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v ProjectValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"created_at":  basetypes.StringType{},
		"description": basetypes.StringType{},
		"id":          basetypes.StringType{},
		"name":        basetypes.StringType{},
		"tags": basetypes.ListType{
			ElemType: types.StringType,
		},
		"updated_at": basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = ServiceAccountType{}

type ServiceAccountType struct {
	basetypes.ObjectType
}

func (t ServiceAccountType) Equal(o attr.Type) bool {
	other, ok := o.(ServiceAccountType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t ServiceAccountType) String() string {
	return "ServiceAccountType"
}

func (t ServiceAccountType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	createdAtAttribute, ok := attributes["created_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`created_at is missing from object`)

		return nil, diags
	}

	createdAtVal, ok := createdAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`created_at expected to be basetypes.StringValue, was: %T`, createdAtAttribute))
	}

	descriptionAttribute, ok := attributes["description"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`description is missing from object`)

		return nil, diags
	}

	descriptionVal, ok := descriptionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`description expected to be basetypes.StringValue, was: %T`, descriptionAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return nil, diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	updatedAtAttribute, ok := attributes["updated_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`updated_at is missing from object`)

		return nil, diags
	}

	updatedAtVal, ok := updatedAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`updated_at expected to be basetypes.StringValue, was: %T`, updatedAtAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return ServiceAccountValue{
		CreatedAt:   createdAtVal,
		Description: descriptionVal,
		Id:          idVal,
		Name:        nameVal,
		UpdatedAt:   updatedAtVal,
		state:       attr.ValueStateKnown,
	}, diags
}

func NewServiceAccountValueNull() ServiceAccountValue {
	return ServiceAccountValue{
		state: attr.ValueStateNull,
	}
}

func NewServiceAccountValueUnknown() ServiceAccountValue {
	return ServiceAccountValue{
		state: attr.ValueStateUnknown,
	}
}

func NewServiceAccountValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (ServiceAccountValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing ServiceAccountValue Attribute Value",
				"While creating a ServiceAccountValue value, a missing attribute value was detected. "+
					"A ServiceAccountValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ServiceAccountValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid ServiceAccountValue Attribute Type",
				"While creating a ServiceAccountValue value, an invalid attribute value was detected. "+
					"A ServiceAccountValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ServiceAccountValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("ServiceAccountValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra ServiceAccountValue Attribute Value",
				"While creating a ServiceAccountValue value, an extra attribute value was detected. "+
					"A ServiceAccountValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra ServiceAccountValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewServiceAccountValueUnknown(), diags
	}

	createdAtAttribute, ok := attributes["created_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`created_at is missing from object`)

		return NewServiceAccountValueUnknown(), diags
	}

	createdAtVal, ok := createdAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`created_at expected to be basetypes.StringValue, was: %T`, createdAtAttribute))
	}

	descriptionAttribute, ok := attributes["description"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`description is missing from object`)

		return NewServiceAccountValueUnknown(), diags
	}

	descriptionVal, ok := descriptionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`description expected to be basetypes.StringValue, was: %T`, descriptionAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return NewServiceAccountValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return NewServiceAccountValueUnknown(), diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	updatedAtAttribute, ok := attributes["updated_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`updated_at is missing from object`)

		return NewServiceAccountValueUnknown(), diags
	}

	updatedAtVal, ok := updatedAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`updated_at expected to be basetypes.StringValue, was: %T`, updatedAtAttribute))
	}

	if diags.HasError() {
		return NewServiceAccountValueUnknown(), diags
	}

	return ServiceAccountValue{
		CreatedAt:   createdAtVal,
		Description: descriptionVal,
		Id:          idVal,
		Name:        nameVal,
		UpdatedAt:   updatedAtVal,
		state:       attr.ValueStateKnown,
	}, diags
}

func NewServiceAccountValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) ServiceAccountValue {
	object, diags := NewServiceAccountValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewServiceAccountValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t ServiceAccountType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewServiceAccountValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewServiceAccountValueUnknown(), nil
	}

	if in.IsNull() {
		return NewServiceAccountValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewServiceAccountValueMust(ServiceAccountValue{}.AttributeTypes(ctx), attributes), nil
}

func (t ServiceAccountType) ValueType(ctx context.Context) attr.Value {
	return ServiceAccountValue{}
}

var _ basetypes.ObjectValuable = ServiceAccountValue{}

type ServiceAccountValue struct {
	CreatedAt   basetypes.StringValue `tfsdk:"created_at"`
	Description basetypes.StringValue `tfsdk:"description"`
	Id          basetypes.StringValue `tfsdk:"id"`
	Name        basetypes.StringValue `tfsdk:"name"`
	UpdatedAt   basetypes.StringValue `tfsdk:"updated_at"`
	state       attr.ValueState
}

func (v ServiceAccountValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 5)

	var val tftypes.Value
	var err error

	attrTypes["created_at"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["description"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["updated_at"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 5)

		val, err = v.CreatedAt.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["created_at"] = val

		val, err = v.Description.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["description"] = val

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		val, err = v.Name.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["name"] = val

		val, err = v.UpdatedAt.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["updated_at"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v ServiceAccountValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v ServiceAccountValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v ServiceAccountValue) String() string {
	return "ServiceAccountValue"
}

func (v ServiceAccountValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"created_at":  basetypes.StringType{},
		"description": basetypes.StringType{},
		"id":          basetypes.StringType{},
		"name":        basetypes.StringType{},
		"updated_at":  basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"created_at":  v.CreatedAt,
			"description": v.Description,
			"id":          v.Id,
			"name":        v.Name,
			"updated_at":  v.UpdatedAt,
		})

	return objVal, diags
}

func (v ServiceAccountValue) Equal(o attr.Value) bool {
	other, ok := o.(ServiceAccountValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.CreatedAt.Equal(other.CreatedAt) {
		return false
	}

	if !v.Description.Equal(other.Description) {
		return false
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.Name.Equal(other.Name) {
		return false
	}

	if !v.UpdatedAt.Equal(other.UpdatedAt) {
		return false
	}

	return true
}

func (v ServiceAccountValue) Type(ctx context.Context) attr.Type {
	return ServiceAccountType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v ServiceAccountValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"created_at":  basetypes.StringType{},
		"description": basetypes.StringType{},
		"id":          basetypes.StringType{},
		"name":        basetypes.StringType{},
		"updated_at":  basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = UserMembershipType{}

type UserMembershipType struct {
	basetypes.ObjectType
}

func (t UserMembershipType) Equal(o attr.Type) bool {
	other, ok := o.(UserMembershipType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t UserMembershipType) String() string {
	return "UserMembershipType"
}

func (t UserMembershipType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	membershipTypeAttribute, ok := attributes["membership_type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`membership_type is missing from object`)

		return nil, diags
	}

	membershipTypeVal, ok := membershipTypeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`membership_type expected to be basetypes.StringValue, was: %T`, membershipTypeAttribute))
	}

	permissionsAttribute, ok := attributes["permissions"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`permissions is missing from object`)

		return nil, diags
	}

	permissionsVal, ok := permissionsAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`permissions expected to be basetypes.ListValue, was: %T`, permissionsAttribute))
	}

	projectAttribute, ok := attributes["project"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`project is missing from object`)

		return nil, diags
	}

	projectVal, ok := projectAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`project expected to be basetypes.ObjectValue, was: %T`, projectAttribute))
	}

	projectIdAttribute, ok := attributes["project_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`project_id is missing from object`)

		return nil, diags
	}

	projectIdVal, ok := projectIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`project_id expected to be basetypes.StringValue, was: %T`, projectIdAttribute))
	}

	projectNameAttribute, ok := attributes["project_name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`project_name is missing from object`)

		return nil, diags
	}

	projectNameVal, ok := projectNameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`project_name expected to be basetypes.StringValue, was: %T`, projectNameAttribute))
	}

	userAttribute, ok := attributes["user"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`user is missing from object`)

		return nil, diags
	}

	userVal, ok := userAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`user expected to be basetypes.ObjectValue, was: %T`, userAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return UserMembershipValue{
		MembershipType: membershipTypeVal,
		Permissions:    permissionsVal,
		Project:        projectVal,
		ProjectId:      projectIdVal,
		ProjectName:    projectNameVal,
		User:           userVal,
		state:          attr.ValueStateKnown,
	}, diags
}

func NewUserMembershipValueNull() UserMembershipValue {
	return UserMembershipValue{
		state: attr.ValueStateNull,
	}
}

func NewUserMembershipValueUnknown() UserMembershipValue {
	return UserMembershipValue{
		state: attr.ValueStateUnknown,
	}
}

func NewUserMembershipValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (UserMembershipValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing UserMembershipValue Attribute Value",
				"While creating a UserMembershipValue value, a missing attribute value was detected. "+
					"A UserMembershipValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("UserMembershipValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid UserMembershipValue Attribute Type",
				"While creating a UserMembershipValue value, an invalid attribute value was detected. "+
					"A UserMembershipValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("UserMembershipValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("UserMembershipValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra UserMembershipValue Attribute Value",
				"While creating a UserMembershipValue value, an extra attribute value was detected. "+
					"A UserMembershipValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra UserMembershipValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewUserMembershipValueUnknown(), diags
	}

	membershipTypeAttribute, ok := attributes["membership_type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`membership_type is missing from object`)

		return NewUserMembershipValueUnknown(), diags
	}

	membershipTypeVal, ok := membershipTypeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`membership_type expected to be basetypes.StringValue, was: %T`, membershipTypeAttribute))
	}

	permissionsAttribute, ok := attributes["permissions"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`permissions is missing from object`)

		return NewUserMembershipValueUnknown(), diags
	}

	permissionsVal, ok := permissionsAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`permissions expected to be basetypes.ListValue, was: %T`, permissionsAttribute))
	}

	projectAttribute, ok := attributes["project"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`project is missing from object`)

		return NewUserMembershipValueUnknown(), diags
	}

	projectVal, ok := projectAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`project expected to be basetypes.ObjectValue, was: %T`, projectAttribute))
	}

	projectIdAttribute, ok := attributes["project_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`project_id is missing from object`)

		return NewUserMembershipValueUnknown(), diags
	}

	projectIdVal, ok := projectIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`project_id expected to be basetypes.StringValue, was: %T`, projectIdAttribute))
	}

	projectNameAttribute, ok := attributes["project_name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`project_name is missing from object`)

		return NewUserMembershipValueUnknown(), diags
	}

	projectNameVal, ok := projectNameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`project_name expected to be basetypes.StringValue, was: %T`, projectNameAttribute))
	}

	userAttribute, ok := attributes["user"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`user is missing from object`)

		return NewUserMembershipValueUnknown(), diags
	}

	userVal, ok := userAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`user expected to be basetypes.ObjectValue, was: %T`, userAttribute))
	}

	if diags.HasError() {
		return NewUserMembershipValueUnknown(), diags
	}

	return UserMembershipValue{
		MembershipType: membershipTypeVal,
		Permissions:    permissionsVal,
		Project:        projectVal,
		ProjectId:      projectIdVal,
		ProjectName:    projectNameVal,
		User:           userVal,
		state:          attr.ValueStateKnown,
	}, diags
}

func NewUserMembershipValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) UserMembershipValue {
	object, diags := NewUserMembershipValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewUserMembershipValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t UserMembershipType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewUserMembershipValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewUserMembershipValueUnknown(), nil
	}

	if in.IsNull() {
		return NewUserMembershipValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewUserMembershipValueMust(UserMembershipValue{}.AttributeTypes(ctx), attributes), nil
}

func (t UserMembershipType) ValueType(ctx context.Context) attr.Value {
	return UserMembershipValue{}
}

var _ basetypes.ObjectValuable = UserMembershipValue{}

type UserMembershipValue struct {
	MembershipType basetypes.StringValue `tfsdk:"membership_type"`
	Permissions    basetypes.ListValue   `tfsdk:"permissions"`
	Project        basetypes.ObjectValue `tfsdk:"project"`
	ProjectId      basetypes.StringValue `tfsdk:"project_id"`
	ProjectName    basetypes.StringValue `tfsdk:"project_name"`
	User           basetypes.ObjectValue `tfsdk:"user"`
	state          attr.ValueState
}

func (v UserMembershipValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 6)

	var val tftypes.Value
	var err error

	attrTypes["membership_type"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["permissions"] = basetypes.ListType{
		ElemType: types.StringType,
	}.TerraformType(ctx)
	attrTypes["project"] = basetypes.ObjectType{
		AttrTypes: ProjectValue{}.AttributeTypes(ctx),
	}.TerraformType(ctx)
	attrTypes["project_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["project_name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["user"] = basetypes.ObjectType{
		AttrTypes: UserValue{}.AttributeTypes(ctx),
	}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 6)

		val, err = v.MembershipType.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["membership_type"] = val

		val, err = v.Permissions.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["permissions"] = val

		val, err = v.Project.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["project"] = val

		val, err = v.ProjectId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["project_id"] = val

		val, err = v.ProjectName.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["project_name"] = val

		val, err = v.User.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["user"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v UserMembershipValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v UserMembershipValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v UserMembershipValue) String() string {
	return "UserMembershipValue"
}

func (v UserMembershipValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	var project basetypes.ObjectValue

	if v.Project.IsNull() {
		project = types.ObjectNull(
			ProjectValue{}.AttributeTypes(ctx),
		)
	}

	if v.Project.IsUnknown() {
		project = types.ObjectUnknown(
			ProjectValue{}.AttributeTypes(ctx),
		)
	}

	if !v.Project.IsNull() && !v.Project.IsUnknown() {
		project = types.ObjectValueMust(
			ProjectValue{}.AttributeTypes(ctx),
			v.Project.Attributes(),
		)
	}

	var user basetypes.ObjectValue

	if v.User.IsNull() {
		user = types.ObjectNull(
			UserValue{}.AttributeTypes(ctx),
		)
	}

	if v.User.IsUnknown() {
		user = types.ObjectUnknown(
			UserValue{}.AttributeTypes(ctx),
		)
	}

	if !v.User.IsNull() && !v.User.IsUnknown() {
		user = types.ObjectValueMust(
			UserValue{}.AttributeTypes(ctx),
			v.User.Attributes(),
		)
	}

	var permissionsVal basetypes.ListValue
	switch {
	case v.Permissions.IsUnknown():
		permissionsVal = types.ListUnknown(types.StringType)
	case v.Permissions.IsNull():
		permissionsVal = types.ListNull(types.StringType)
	default:
		var d diag.Diagnostics
		permissionsVal, d = types.ListValue(types.StringType, v.Permissions.Elements())
		diags.Append(d...)
	}

	if diags.HasError() {
		return types.ObjectUnknown(map[string]attr.Type{
			"membership_type": basetypes.StringType{},
			"permissions": basetypes.ListType{
				ElemType: types.StringType,
			},
			"project": basetypes.ObjectType{
				AttrTypes: ProjectValue{}.AttributeTypes(ctx),
			},
			"project_id":   basetypes.StringType{},
			"project_name": basetypes.StringType{},
			"user": basetypes.ObjectType{
				AttrTypes: UserValue{}.AttributeTypes(ctx),
			},
		}), diags
	}

	attributeTypes := map[string]attr.Type{
		"membership_type": basetypes.StringType{},
		"permissions": basetypes.ListType{
			ElemType: types.StringType,
		},
		"project": basetypes.ObjectType{
			AttrTypes: ProjectValue{}.AttributeTypes(ctx),
		},
		"project_id":   basetypes.StringType{},
		"project_name": basetypes.StringType{},
		"user": basetypes.ObjectType{
			AttrTypes: UserValue{}.AttributeTypes(ctx),
		},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"membership_type": v.MembershipType,
			"permissions":     permissionsVal,
			"project":         project,
			"project_id":      v.ProjectId,
			"project_name":    v.ProjectName,
			"user":            user,
		})

	return objVal, diags
}

func (v UserMembershipValue) Equal(o attr.Value) bool {
	other, ok := o.(UserMembershipValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.MembershipType.Equal(other.MembershipType) {
		return false
	}

	if !v.Permissions.Equal(other.Permissions) {
		return false
	}

	if !v.Project.Equal(other.Project) {
		return false
	}

	if !v.ProjectId.Equal(other.ProjectId) {
		return false
	}

	if !v.ProjectName.Equal(other.ProjectName) {
		return false
	}

	if !v.User.Equal(other.User) {
		return false
	}

	return true
}

func (v UserMembershipValue) Type(ctx context.Context) attr.Type {
	return UserMembershipType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v UserMembershipValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"membership_type": basetypes.StringType{},
		"permissions": basetypes.ListType{
			ElemType: types.StringType,
		},
		"project": basetypes.ObjectType{
			AttrTypes: ProjectValue{}.AttributeTypes(ctx),
		},
		"project_id":   basetypes.StringType{},
		"project_name": basetypes.StringType{},
		"user": basetypes.ObjectType{
			AttrTypes: UserValue{}.AttributeTypes(ctx),
		},
	}
}

var _ basetypes.ObjectTypable = ProjectType{}

var _ basetypes.ObjectValuable = ProjectValue{}

var _ basetypes.ObjectTypable = UserType{}

type UserType struct {
	basetypes.ObjectType
}

func (t UserType) Equal(o attr.Type) bool {
	other, ok := o.(UserType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t UserType) String() string {
	return "UserType"
}

func (t UserType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	emailAttribute, ok := attributes["email"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`email is missing from object`)

		return nil, diags
	}

	emailVal, ok := emailAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`email expected to be basetypes.StringValue, was: %T`, emailAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return UserValue{
		Email: emailVal,
		Id:    idVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewUserValueNull() UserValue {
	return UserValue{
		state: attr.ValueStateNull,
	}
}

func NewUserValueUnknown() UserValue {
	return UserValue{
		state: attr.ValueStateUnknown,
	}
}

func NewUserValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (UserValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing UserValue Attribute Value",
				"While creating a UserValue value, a missing attribute value was detected. "+
					"A UserValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("UserValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid UserValue Attribute Type",
				"While creating a UserValue value, an invalid attribute value was detected. "+
					"A UserValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("UserValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("UserValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra UserValue Attribute Value",
				"While creating a UserValue value, an extra attribute value was detected. "+
					"A UserValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra UserValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewUserValueUnknown(), diags
	}

	emailAttribute, ok := attributes["email"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`email is missing from object`)

		return NewUserValueUnknown(), diags
	}

	emailVal, ok := emailAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`email expected to be basetypes.StringValue, was: %T`, emailAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return NewUserValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	if diags.HasError() {
		return NewUserValueUnknown(), diags
	}

	return UserValue{
		Email: emailVal,
		Id:    idVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewUserValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) UserValue {
	object, diags := NewUserValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewUserValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t UserType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewUserValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewUserValueUnknown(), nil
	}

	if in.IsNull() {
		return NewUserValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewUserValueMust(UserValue{}.AttributeTypes(ctx), attributes), nil
}

func (t UserType) ValueType(ctx context.Context) attr.Value {
	return UserValue{}
}

var _ basetypes.ObjectValuable = UserValue{}

type UserValue struct {
	Email basetypes.StringValue `tfsdk:"email"`
	Id    basetypes.StringValue `tfsdk:"id"`
	state attr.ValueState
}

func (v UserValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["email"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["id"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.Email.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["email"] = val

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v UserValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v UserValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v UserValue) String() string {
	return "UserValue"
}

func (v UserValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"email": basetypes.StringType{},
		"id":    basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"email": v.Email,
			"id":    v.Id,
		})

	return objVal, diags
}

func (v UserValue) Equal(o attr.Value) bool {
	other, ok := o.(UserValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Email.Equal(other.Email) {
		return false
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	return true
}

func (v UserValue) Type(ctx context.Context) attr.Type {
	return UserType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v UserValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"email": basetypes.StringType{},
		"id":    basetypes.StringType{},
	}
}
