provider:
  name: sys11iam
resources:
  organization:
    create:
      path: /v2/orgs
      method: POST
    read:
      path: /v2/orgs/{organization_id}
      method: GET
    update:
      path: /v2/orgs/{organization_id}
      method: PUT
    delete:
      path: /v2/orgs/{organization_id}
      method: DELETE
  project:
    create:
      path: /v2/orgs/{organization_id}/projects
      method: POST
    read:
      path: /v2/orgs/{organization_id}/projects/{project_id}
      method: GET
    update:
      path: /v2/orgs/{organization_id}/projects/{project_id}
      method: PUT
    delete:
      path: /v2/orgs/{organization_id}/projects/{project_id}
      method: DELETE
  organization_membership:
    create:
      path: /v2/orgs/{organization_id}/memberships/{member_id}
      method: PATCH
    read:
      path: /v2/orgs/{organization_id}/memberships/{member_id}
      method: GET
    delete:
      path: /v2/orgs/{organization_id}/memberships/{member_id}
      method: DELETE
  organization_membership_permission:
    create:
      path: /v2/orgs/{organization_id}/memberships/{member_id}/permissions
      method: POST
    read:
      path: /v2/orgs/{organization_id}/memberships/{member_id}
      method: GET
    delete:
      path: /v2/orgs/{organization_id}/memberships/{member_id}/permissions
      method: DELETE
  project_membership:
    create:
      path: /v2/orgs/{organization_id}/projects/{project_id}/memberships/{member_id}
      method: PATCH
    read:
      path: /v2/orgs/{organization_id}/projects/{project_id}/memberships/{member_id}
      method: GET
    update:
      path: /v2/orgs/{organization_id}/projects/{project_id}/memberships/{member_id}
      method: PATCH
    delete:
      path: /v2/orgs/{organization_id}/projects/{project_id}/memberships/{member_id}
      method: DELETE
  project_membership_permission:
    create:
      path: /v2/orgs/{organization_id}/projects/{project_id}/memberships/{member_id}/permissions
      method: POST
    read:
      path: /v2/orgs/{organization_id}/projects/{project_id}/memberships/{member_id}
      method: GET
    delete:
      path: /v2/orgs/{organization_id}/projects/{project_id}/memberships/{member_id}/permissions
      method: DELETE
  project_s3_user:
    create:
      path: /v2/orgs/{organization_id}/projects/{project_id}/s3-users
      method: POST
    read:
      path: /v2/orgs/{organization_id}/projects/{project_id}/s3-users/{s3_user_id}
      method: GET
    update:
      path: /v2/orgs/{organization_id}/projects/{project_id}/s3-users/{s3_user_id}
      method: PUT
  project_s3_user_key:
    create:
      path: /v2/orgs/{organization_id}/projects/{project_id}/s3-users/{s3_user_id}/ec2-credentials
      method: POST
    read:
      path: /v2/orgs/{organization_id}/projects/{project_id}/s3-users/{s3_user_id}/ec2-credentials/{s3_access_key}
      method: GET
    delete:
      path: /v2/orgs/{organization_id}/projects/{project_id}/s3-users/{s3_user_id}/ec2-credentials/{s3_access_key}
      method: DELETE

