provider:
  name: ncs
resources:
  organization:
    create:
      path: /v1/orgs
      method: POST
    read:
      path: /v1/orgs/{organization_id}
      method: GET
    update:
      path: /v1/orgs/{organization_id}
      method: PUT
    delete:
      path: /v1/orgs/{organization_id}
      method: DELETE
  project:
    create:
      path: /v1/orgs/{organization_id}/projects
      method: POST
    read:
      path: /v1/orgs/{organization_id}/projects/{project_id}
      method: GET
    update:
      path: /v1/orgs/{organization_id}/projects/{project_id}
      method: PUT
    delete:
      path: /v1/orgs/{organization_id}/projects/{project_id}
      method: DELETE
  organization_membership:
    create:
      path: /v1/orgs/{organization_id}/memberships/{user_id}/permissions
      method: PUT
    read:
      path: /v1/orgs/{organization_id}/memberships/{user_id}
      method: GET
    update:
      path: /v1/orgs/{organization_id}/memberships/{user_id}/permissions
      method: PUT
    delete:
      path: /v1/orgs/{organization_id}/memberships/{user_id}
      method: DELETE
  project_membership:
    create:
      path: /v1/orgs/{organization_id}/projects/{project_id}/memberships/{user_id}/permissions
      method: PUT
    read:
      path: /v1/orgs/{organization_id}/projects/{project_id}/memberships/{user_id}
      method: GET
    update:
      path: /v1/orgs/{organization_id}/projects/{project_id}/memberships/{user_id}/permissions
      method: PUT
    delete:
      path: /v1/orgs/{organization_id}/projects/{project_id}/memberships/{user_id}
      method: DELETE