provider:
  name: sys11iam
resources:
  organization:
    create:
      path: /v3/orgs
      method: POST
    read:
      path: /v3/orgs/{org_id}
      method: GET
    update:
      path: /v3/orgs/{org_id}
      method: PUT
    delete:
      path: /v3/orgs/{org_id}
      method: DELETE
  organization_project:
    create:
      path: /v3/orgs/{org_id}/projects
      method: POST
    read:
      path: /v3/orgs/{org_id}/projects/{project_id}
      method: GET
    update:
      path: /v3/orgs/{org_id}/projects/{project_id}
      method: PUT
    delete:
      path: /v3/orgs/{org_id}/projects/{project_id}
      method: DELETE
  organization_project_s3_user:
    create:
      path: /v3/orgs/{org_id}/projects/{project_id}/s3-users
      method: POST
    read:
      path: /v3/orgs/{org_id}/projects/{project_id}/s3-users/{s3_user_id}
      method: GET
    update:
      path: /v3/orgs/{org_id}/projects/{project_id}/s3-users/{user_id}
      method: PUT
  organization_project_s3_user_key:
    create:
      path: /v3/orgs/{org_id}/projects/{project_id}/s3-users/{user_id}/ec2-credentials
      method: POST
    read:
      path: /v3/orgs/{org_id}/projects/{project_id}/s3-users/{user_id}/ec2-credentials/{access_key}
      method: GET
    delete:
      path: /v3/orgs/{org_id}/projects/{project_id}/s3-users/{user_id}/ec2-credentials/{access_key}
      method: DELETE
  organization_contact:
    create:
      path: /v3/orgs/{org_id}/contacts
      method: POST
    read:
      path: /v3/orgs/{org_id}/contacts/{contact_id}
      method: GET
    update:
      path: /v3/orgs/{org_id}/contacts/{contact_id}
      method: PUT
    delete:
      path: /v3/orgs/{org_id}/contacts/{contact_id}
      method: DELETE
  organization_serviceaccount:
    create:
      path: /v3/orgs/{org_id}/service_accounts
      method: POST
    read:
      path: /v3/orgs/{org_id}/service_accounts/{service_account_id}
      method: GET
    update:
      path: /v3/orgs/{org_id}/service_accounts/{service_account_id}
      method: PUT
    delete:
      path: /v3/orgs/{org_id}/service_accounts/{service_account_id}
      method: DELETE
  organization_team:
    create:
      path: /v3/orgs/{org_id}/teams
      method: POST
    read:
      path: /v3/orgs/{org_id}/teams/{team_id}
      method: GET
    update:
      path: /v3/orgs/{org_id}/teams/{team_id}
      method: PUT
    delete:
      path: /v3/orgs/{org_id}/teams/{team_id}
      method: DELETE
