// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_organization_membership

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func OrganizationMembershipResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"editable_permissions": schema.ListAttribute{
				ElementType:         types.StringType,
				Required:            true,
				Description:         "The editable permissions of the user",
				MarkdownDescription: "The editable permissions of the user",
			},
			"email": schema.StringAttribute{
				Required:            true,
				Description:         "The email of the user",
				MarkdownDescription: "The email of the user",
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "The UUID of the user",
				MarkdownDescription: "The UUID of the user",
			},
			"organization_id": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
		},
	}
}

type OrganizationMembershipModel struct {
	EditablePermissions    types.List   `tfsdk:"editable_permissions"`
	Email                  types.String `tfsdk:"email"`
	Id                     types.String `tfsdk:"id"`
	OrganizationId         types.String `tfsdk:"organization_id"`
}
