// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_organization_membership

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

func OrganizationMembershipResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"affiliation": schema.StringAttribute{
				Required:            true,
				Description:         "The affiliation of the user to this organization. This is not to be understood as a role.",
				MarkdownDescription: "The affiliation of the user to this organization. This is not to be understood as a role.",
			},
			"editable_permissions": schema.ListAttribute{
				ElementType:         types.StringType,
				Required:            true,
				Description:         "The editable permissions of the user",
				MarkdownDescription: "The editable permissions of the user",
			},
			"email": schema.StringAttribute{
				Required:            true,
				Description:         "The email of the user",
				MarkdownDescription: "The email of the user",
			},
			"id": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The UUID of the user",
				MarkdownDescription: "The UUID of the user",
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"organization_id": schema.StringAttribute{
				Required: true,
			},
			"is_active": schema.BoolAttribute{
				Computed:            true,
				Default:             booldefault.StaticBool(false),
				Description:         "Whether the member is active or not.",
				MarkdownDescription: "Whether the member is active or not.",
				PlanModifiers:       []planmodifier.Bool{UseStateForUnknown()},
			},
		},
	}
}

type OrganizationMembershipModel struct {
	Affiliation         types.String `tfsdk:"affiliation"`
	EditablePermissions types.List   `tfsdk:"editable_permissions"`
	Email               types.String `tfsdk:"email"`
	Id                  types.String `tfsdk:"id"`
	OrganizationId      types.String `tfsdk:"organization_id"`
	IsActive            types.Bool   `tfsdk:"is_active"`
}
