// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_organization_team_membership

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
)

func OrganizationTeamMembershipResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"editable_permissions": schema.ListAttribute{
				ElementType:         types.StringType,
				Required:            true,
				Description:         "The editable permissions of the user",
				MarkdownDescription: "The editable permissions of the user",
			},
			"id": schema.StringAttribute{
				Optional: 			 true,
				Computed:            true,
				Description:         "The UUID of the user",
				MarkdownDescription: "The UUID of the user",
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"organization_id": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"team_id": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
		},
	}
}

type OrganizationTeamMembershipModel struct {
	EditablePermissions    types.List   `tfsdk:"editable_permissions"`
	Id                     types.String `tfsdk:"id"`
	OrganizationId         types.String `tfsdk:"organization_id"`
	TeamId         types.String `tfsdk:"team_id"`
}
