// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_organization_serviceaccount

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

func OrganizationServiceaccountResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "The name of the service-account",
				MarkdownDescription: "The name of the service-account",
			},
			"description": schema.StringAttribute{
				Required:            true,
				Description:         "The description of the service-account",
				MarkdownDescription: "The description of the service-account",
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "The UUID of the service-account",
				MarkdownDescription: "The UUID of the service-account",
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"organization_id": schema.StringAttribute{
				Required: true,
			},
		},
	}
}

type OrganizationServiceaccountModel struct {
	Name           types.String `tfsdk:"name"`
	Description    types.String `tfsdk:"description"`
	Id             types.String `tfsdk:"id"`
	OrganizationId types.String `tfsdk:"organization_id"`
}
