// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_organization_serviceaccount

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func OrganizationServiceaccountResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"created_at": schema.StringAttribute{
				Computed: true,
			},
			"description": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The description of the service account.",
				MarkdownDescription: "The description of the service account.",
				Default:             stringdefault.StaticString(""),
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "The UUID of the service account.",
				MarkdownDescription: "The UUID of the service account.",
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "The unique name of the service account.",
				MarkdownDescription: "The unique name of the service account.",
			},
			"org_id": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"service_account_id": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"updated_at": schema.StringAttribute{
				Computed: true,
			},
		},
	}
}

type OrganizationServiceaccountModel struct {
	CreatedAt        types.String `tfsdk:"created_at"`
	Description      types.String `tfsdk:"description"`
	Id               types.String `tfsdk:"id"`
	Name             types.String `tfsdk:"name"`
	OrgId            types.String `tfsdk:"org_id"`
	ServiceAccountId types.String `tfsdk:"service_account_id"`
	UpdatedAt        types.String `tfsdk:"updated_at"`
}
