// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_project_membership

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

func ProjectMembershipResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"email": schema.StringAttribute{
				Required:            true,
				Description:         "The email address of the user.",
				MarkdownDescription: "The email address of the user.",
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "The UUID of the user.",
				MarkdownDescription: "The UUID of the user.",
			},
			"organization_id": schema.StringAttribute{
				Required: true,
			},
			"permissions": schema.ListAttribute{
				Required:            true,
				ElementType:         types.StringType,
				Description:         "The permissions of the user",
				MarkdownDescription: "The permissions of the user",
			},
			"project_id": schema.StringAttribute{
				Required:            true,
				Description:         "The UUID of the project",
				MarkdownDescription: "The UUID of the project",
			},
		},
	}
}

type ProjectMembershipModel struct {
	Email          types.String `tfsdk:"email"`
	Id             types.String `tfsdk:"id"`
	OrganizationId types.String `tfsdk:"organization_id"`
	Permissions    types.List   `tfsdk:"permissions"`
	ProjectId      types.String `tfsdk:"project_id"`
}
