// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_organization_project_s3_user

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"regexp"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func OrganizationProjectS3UserResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"description": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The description of the user.",
				MarkdownDescription: "The description of the user.",
				Validators: []validator.String{
					stringvalidator.LengthAtMost(1000),
					stringvalidator.RegexMatches(regexp.MustCompile("^[^\\u0000]*$"), ""),
				},
				Default: stringdefault.StaticString(""),
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "The user id.",
				MarkdownDescription: "The user id.",
			},
			"keys": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"access_key": schema.StringAttribute{
							Computed:            true,
							Description:         "The user's access key.",
							MarkdownDescription: "The user's access key.",
						},
						"created_at": schema.StringAttribute{
							Computed:            true,
							Description:         "The time the resource was created.",
							MarkdownDescription: "The time the resource was created.",
						},
					},
					CustomType: KeysType{
						ObjectType: types.ObjectType{
							AttrTypes: KeysValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed:            true,
				Description:         "The user's S3 keys (access keys only).",
				MarkdownDescription: "The user's S3 keys (access keys only).",
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "The name of the user.",
				MarkdownDescription: "The name of the user.",
				Validators: []validator.String{
					stringvalidator.LengthBetween(3, 62),
					stringvalidator.RegexMatches(regexp.MustCompile("^[a-z0-9]+(?:-[a-z0-9]+)*$"), ""),
				},
			},
		},
	}
}

type OrganizationProjectS3UserModel struct {
	Description types.String `tfsdk:"description"`
	Id          types.String `tfsdk:"id"`
	Keys        types.List   `tfsdk:"keys"`
	Name        types.String `tfsdk:"name"`
}

var _ basetypes.ObjectTypable = KeysType{}

type KeysType struct {
	basetypes.ObjectType
}

func (t KeysType) Equal(o attr.Type) bool {
	other, ok := o.(KeysType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t KeysType) String() string {
	return "KeysType"
}

func (t KeysType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	accessKeyAttribute, ok := attributes["access_key"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`access_key is missing from object`)

		return nil, diags
	}

	accessKeyVal, ok := accessKeyAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`access_key expected to be basetypes.StringValue, was: %T`, accessKeyAttribute))
	}

	createdAtAttribute, ok := attributes["created_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`created_at is missing from object`)

		return nil, diags
	}

	createdAtVal, ok := createdAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`created_at expected to be basetypes.StringValue, was: %T`, createdAtAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return KeysValue{
		AccessKey: accessKeyVal,
		CreatedAt: createdAtVal,
		state:     attr.ValueStateKnown,
	}, diags
}

func NewKeysValueNull() KeysValue {
	return KeysValue{
		state: attr.ValueStateNull,
	}
}

func NewKeysValueUnknown() KeysValue {
	return KeysValue{
		state: attr.ValueStateUnknown,
	}
}

func NewKeysValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (KeysValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing KeysValue Attribute Value",
				"While creating a KeysValue value, a missing attribute value was detected. "+
					"A KeysValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("KeysValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid KeysValue Attribute Type",
				"While creating a KeysValue value, an invalid attribute value was detected. "+
					"A KeysValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("KeysValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("KeysValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra KeysValue Attribute Value",
				"While creating a KeysValue value, an extra attribute value was detected. "+
					"A KeysValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra KeysValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewKeysValueUnknown(), diags
	}

	accessKeyAttribute, ok := attributes["access_key"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`access_key is missing from object`)

		return NewKeysValueUnknown(), diags
	}

	accessKeyVal, ok := accessKeyAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`access_key expected to be basetypes.StringValue, was: %T`, accessKeyAttribute))
	}

	createdAtAttribute, ok := attributes["created_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`created_at is missing from object`)

		return NewKeysValueUnknown(), diags
	}

	createdAtVal, ok := createdAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`created_at expected to be basetypes.StringValue, was: %T`, createdAtAttribute))
	}

	if diags.HasError() {
		return NewKeysValueUnknown(), diags
	}

	return KeysValue{
		AccessKey: accessKeyVal,
		CreatedAt: createdAtVal,
		state:     attr.ValueStateKnown,
	}, diags
}

func NewKeysValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) KeysValue {
	object, diags := NewKeysValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewKeysValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t KeysType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewKeysValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewKeysValueUnknown(), nil
	}

	if in.IsNull() {
		return NewKeysValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewKeysValueMust(KeysValue{}.AttributeTypes(ctx), attributes), nil
}

func (t KeysType) ValueType(ctx context.Context) attr.Value {
	return KeysValue{}
}

var _ basetypes.ObjectValuable = KeysValue{}

type KeysValue struct {
	AccessKey basetypes.StringValue `tfsdk:"access_key"`
	CreatedAt basetypes.StringValue `tfsdk:"created_at"`
	state     attr.ValueState
}

func (v KeysValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["access_key"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["created_at"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.AccessKey.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["access_key"] = val

		val, err = v.CreatedAt.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["created_at"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v KeysValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v KeysValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v KeysValue) String() string {
	return "KeysValue"
}

func (v KeysValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"access_key": basetypes.StringType{},
		"created_at": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"access_key": v.AccessKey,
			"created_at": v.CreatedAt,
		})

	return objVal, diags
}

func (v KeysValue) Equal(o attr.Value) bool {
	other, ok := o.(KeysValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.AccessKey.Equal(other.AccessKey) {
		return false
	}

	if !v.CreatedAt.Equal(other.CreatedAt) {
		return false
	}

	return true
}

func (v KeysValue) Type(ctx context.Context) attr.Type {
	return KeysType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v KeysValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"access_key": basetypes.StringType{},
		"created_at": basetypes.StringType{},
	}
}
