// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_organization_team_permission

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func OrganizationTeamPermissionResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"added_permissions": schema.ListAttribute{
				ElementType:         types.StringType,
				Computed:            true,
				Description:         "The added organization permissions of the team",
				MarkdownDescription: "The added organization permissions of the team",
			},
			"org_id": schema.StringAttribute{
				Computed:            true,
				Description:         "The id of the organization",
				MarkdownDescription: "The id of the organization",
			},
			"organization_id": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"removed_permissions": schema.ListAttribute{
				ElementType:         types.StringType,
				Computed:            true,
				Description:         "The removed organization permissions of the team",
				MarkdownDescription: "The removed organization permissions of the team",
			},
			"team_id": schema.StringAttribute{
				Computed:            true,
				Description:         "The id of the team",
				MarkdownDescription: "The id of the team",
			},
			"updated_permissions": schema.ListAttribute{
				ElementType:         types.StringType,
				Computed:            true,
				Description:         "The permissions the team currently has.",
				MarkdownDescription: "The permissions the team currently has.",
			},
		},
	}
}

type OrganizationTeamPermissionModel struct {
	AddedPermissions   types.List   `tfsdk:"added_permissions"`
	OrgId              types.String `tfsdk:"org_id"`
	OrganizationId     types.String `tfsdk:"organization_id"`
	RemovedPermissions types.List   `tfsdk:"removed_permissions"`
	TeamId             types.String `tfsdk:"team_id"`
	UpdatedPermissions types.List   `tfsdk:"updated_permissions"`
}
