// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_organization_team

import (
	"context"
	"regexp"

	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

func OrganizationTeamResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"editable_permissions": schema.ListAttribute{
				ElementType:         types.StringType,
				Required:            true,
				Description:         "The editable permissions of the user",
				MarkdownDescription: "The editable permissions of the user",
			},
			"description": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "A description for the team.",
				MarkdownDescription: "A description for the team.",
				Validators: []validator.String{
					stringvalidator.RegexMatches(regexp.MustCompile("^[ -~]*$"), ""),
				},
				Default: stringdefault.StaticString(""),
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "The UUID of the team",
				MarkdownDescription: "The UUID of the team",
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "A unique name for the team.",
				MarkdownDescription: "A unique name for the team.",
				Validators: []validator.String{
					stringvalidator.RegexMatches(regexp.MustCompile("^[ -~]{1,62}$"), ""),
				},
			},
			"tags": schema.ListAttribute{
				ElementType:         types.StringType,
				Optional:            true,
				Computed:            true,
				Description:         "The tags of the team.",
				MarkdownDescription: "The tags of the team.",
			},
			"organization_id": schema.StringAttribute{
				Required: true,
			},
		},
	}
}

type OrganizationTeamModel struct {
	EditablePermissions types.List   `tfsdk:"editable_permissions"`
	Description         types.String `tfsdk:"description"`
	Id                  types.String `tfsdk:"id"`
	Name                types.String `tfsdk:"name"`
	Tags                types.List   `tfsdk:"tags"`
	OrganizationId      types.String `tfsdk:"organization_id"`
}
