// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_organization

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func OrganizationDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"created_at": schema.StringAttribute{
				Computed:            true,
				Description:         "The time the resource was created.",
				MarkdownDescription: "The time the resource was created.",
			},
			"description": schema.StringAttribute{
				Computed:            true,
				Description:         "A description for the organization.",
				MarkdownDescription: "A description for the organization.",
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "The UUID of the organization",
				MarkdownDescription: "The UUID of the organization",
			},
			"is_active": schema.BoolAttribute{
				Computed:            true,
				Description:         "Whether the organization is active or not.",
				MarkdownDescription: "Whether the organization is active or not.",
			},
			"name": schema.StringAttribute{
				Computed:            true,
				Description:         "A unique name for the organization.",
				MarkdownDescription: "A unique name for the organization.",
			},
			"organization_id": schema.StringAttribute{
				Required: true,
			},
			"tags": schema.ListAttribute{
				ElementType:         types.StringType,
				Computed:            true,
				Description:         "The tags of the organization.",
				MarkdownDescription: "The tags of the organization.",
			},
			"updated_at": schema.StringAttribute{
				Computed:            true,
				Description:         "The time the resource was last updated.",
				MarkdownDescription: "The time the resource was last updated.",
			},
		},
	}
}

type OrganizationModel struct {
	CreatedAt      types.String `tfsdk:"created_at"`
	Description    types.String `tfsdk:"description"`
	Id             types.String `tfsdk:"id"`
	IsActive       types.Bool   `tfsdk:"is_active"`
	Name           types.String `tfsdk:"name"`
	OrganizationId types.String `tfsdk:"organization_id"`
	Tags           types.List   `tfsdk:"tags"`
	UpdatedAt      types.String `tfsdk:"updated_at"`
}
